<?php
// install/setup.php
error_reporting(E_ALL);
ini_set('display_errors', 1);

$step = $_GET['step'] ?? 1;
$msg = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (isset($_POST['action']) && $_POST['action'] === 'install') {
        $db_host = $_POST['db_host'];
        $db_name = $_POST['db_name'];
        $db_user = $_POST['db_user'];
        $db_pass = $_POST['db_pass'];
        $base_url = $_POST['base_url'];

        $admin_name = $_POST['admin_name'];
        $admin_email = $_POST['admin_email'];
        $admin_pass = $_POST['admin_pass'];

        // 1. Try Connection
        try {
            $pdo = new PDO("mysql:host=$db_host;charset=utf8mb4", $db_user, $db_pass);
            $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

            // 2. Create DB if not exists (Optional, usually host provides db)
            // Let's assume DB exists or we try to use it.
            $pdo->query("USE `$db_name`");

            // 3. Run SQL
            $sql = file_get_contents(__DIR__ . '/install.sql');
            if (!$sql)
                die("Erro: Arquivo install.sql não encontrado.");

            // Split SQL by ; to execute statements (Basic splitter)
            // PDO doesn't always support multi-query via execute() directly depending on driver headers used in some systems, but properly configured MySQL driver does.
            // Let's try executing full block.
            $pdo->exec($sql);

            // 4. Create Admin
            $hash = password_hash($admin_pass, PASSWORD_DEFAULT);
            $stmt = $pdo->prepare("INSERT INTO users (name, email, password, role, created_at) VALUES (?, ?, ?, 'admin', NOW())");
            $stmt->execute([$admin_name, $admin_email, $hash]);

            // 5. Create Config File
            $config_content = "<?php\n";
            $config_content .= "// Generated by Installer\n\n";
            $config_content .= "define('DB_SERVER', '$db_host');\n";
            $config_content .= "define('DB_USERNAME', '$db_user');\n";
            $config_content .= "define('DB_PASSWORD', '$db_pass');\n";
            $config_content .= "define('DB_NAME', '$db_name');\n\n";
            $config_content .= "define('BASE_URL', '$base_url');\n";
            $config_content .= "define('SITE_NAME', 'Minha Loja');\n";
            $config_content .= "define('WHATSAPP_ADMIN', '');\n"; // Can prompt for this too

            file_put_contents(__DIR__ . '/../config.php', $config_content);

            // 6. Finish
            header("Location: setup.php?step=success");
            exit;

        } catch (Exception $e) {
            $msg = "<div class='alert alert-danger'>Erro: " . $e->getMessage() . "</div>";
        }
    }
}
?>
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <title>Instalador - Catalogo White-Label</title>
    <style>
        body {
            font-family: sans-serif;
            background: #f4f4f4;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            margin: 0;
        }

        .box {
            background: #fff;
            padding: 2rem;
            border-radius: 8px;
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
            width: 100%;
            max-width: 500px;
        }

        h1 {
            margin-top: 0;
            color: #333;
        }

        label {
            display: block;
            margin-top: 1rem;
            font-weight: bold;
            color: #555;
        }

        input {
            width: 100%;
            padding: 10px;
            margin-top: 5px;
            border: 1px solid #ddd;
            border-radius: 4px;
            box-sizing: border-box;
        }

        button {
            background: #28a745;
            color: #fff;
            border: none;
            padding: 12px;
            width: 100%;
            margin-top: 1.5rem;
            border-radius: 4px;
            font-size: 1rem;
            cursor: pointer;
        }

        button:hover {
            background: #218838;
        }

        .alert {
            padding: 10px;
            border-radius: 4px;
            margin-bottom: 1rem;
        }

        .alert-danger {
            background: #f8d7da;
            color: #721c24;
        }

        .alert-success {
            background: #d4edda;
            color: #155724;
        }
    </style>
</head>

<body>

    <div class="box">
        <?php if ($step == 'success'): ?>
            <div style="text-align:center;">
                <h1 style="color:#28a745;">Sucesso! 🚀</h1>
                <p>O sistema foi instalado corretamente.</p>
                <p>Por favor, apague a pasta <code>install/</code> por segurança.</p>
                <a href="../admin/login.php"
                    style="display:block; margin-top:20px; text-decoration:none; color:#007bff; font-weight:bold;">Ir para
                    Login Admin &rarr;</a>
            </div>
        <?php else: ?>
            <h1>Instalação do Catálogo</h1>
            <?php echo $msg; ?>

            <form method="POST">
                <input type="hidden" name="action" value="install">

                <h3>1. Banco de Dados</h3>
                <label>Host do Banco (Ex: localhost)</label>
                <input type="text" name="db_host" value="localhost" required>

                <label>Nome do Banco</label>
                <input type="text" name="db_name" required placeholder="ex: minha_loja">

                <label>Usuário do Banco</label>
                <input type="text" name="db_user" required placeholder="root">

                <label>Senha do Banco</label>
                <input type="password" name="db_pass" placeholder="">

                <h3>2. Configurações da Loja</h3>
                <label>URL Base (Caminho da instalação)</label>
                <input type="text" name="base_url" value="/catalogo" required placeholder="Ex: / ou /loja">

                <h3>3. Criar Administrador</h3>
                <label>Nome</label>
                <input type="text" name="admin_name" required placeholder="Seu Nome">

                <label>Email (Login)</label>
                <input type="email" name="admin_email" required placeholder="admin@loja.com">

                <label>Senha</label>
                <input type="password" name="admin_pass" required>

                <button type="submit">Instalar Agora</button>
            </form>
        <?php endif; ?>
    </div>

</body>

</html>